Repository alexjustesen/speedtest-tracker, pull requests merged in 2022-09, with the labels that each got.

#14 Expanded speedtest results
  app/Jobs/ExecSpeedtest.php
  app/Jobs/SearchForSpeedtests.php
  app/Models/Result.php
  database/factories/ResultFactory.php
  database/migrations/2022_08_31_202106_create_results_table.php
Labels: 🎉 feature

#13 Influxdb support
  app/Console/Commands/TestInfluxDB.php
  app/Models/Result.php
  app/Observers/ResultObserver.php
  app/Providers/EventServiceProvider.php
  composer.json
  composer.lock
  config.example.yml
Labels: 🎉 feature

#18 Some cleanup
  .dockerignore
  .env.example
  README.md
  app/Console/Commands/AppStartupCommand.php
  app/Console/Commands/InstallCommand.php
  app/Console/Commands/TestInfluxDB.php
  app/Jobs/ExecSpeedtest.php
  app/Jobs/SearchForSpeedtests.php
  app/Observers/ResultObserver.php
  composer.json
  composer.lock
  docker-compose.prod.yml
  docker-compose.yml
Labels: 🎉 feature

#21 GDPR ack option
  app/Jobs/ExecSpeedtest.php
  config.example.yml
Labels: 🎉 feature, 👋 good first issue

#27 Filament admin panel
  .phpstorm.meta.php
  _ide_helper.php
  app/Console/Commands/InstallCommand.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Resources/ResultResource/Pages/ListResults.php
  app/Filament/Resources/ResultResource/Widgets/StatsOverview.php
  app/Http/Middleware/Authenticate.php
  app/Models/User.php
  app/Policies/ResultPolicy.php
  app/Providers/FilamentServiceProvider.php
  app/Tables/Columns/BytesColumn.php
  app/helpers.php
  composer.json
  composer.lock
  config/app.php
  config/filament.php
  database/migrations/2022_09_27_212959_create_admin_user.php
  resources/js/app.js
  resources/js/bootstrap.js
  resources/views/tables/columns/bytes-column.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: 🎉 feature

#30 Filament user trait and result stats error
  app/Filament/Resources/ResultResource/Widgets/StatsOverview.php
  app/Models/User.php
Labels: 🐛 bug

#38 Show server in results table
  app/Filament/Resources/ResultResource.php
  app/Tables/Columns/ServerColumn.php
  resources/views/tables/columns/server-column.blade.php
Labels: 🎉 feature
