Repository alexjustesen/speedtest-tracker, pull requests merged in 2022-11, with the labels that each got.

#105 Dependency updates
  _ide_helper.php
  composer.lock
Labels: dependencies

#106 Add a license because it's on the checklist
  LICENSE.md
Labels: 📖 documentation

#107 Create SECURITY.md
  SECURITY.md
Labels: 📖 documentation

#108 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📖 documentation

#109 Create FUNDING.yml
  .github/FUNDING.yml
Labels: 📖 documentation

#110 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📖 documentation

#112 Use config helper for debug policies
  app/Policies/FailedJobPolicy.php
  app/Providers/FilamentServiceProvider.php
Labels: 🐛 bug

#117 Disabled crontab mail
  docker/8.1/cron/scheduler
  docker/deploy/cron/scheduler
Labels: 🐛 bug

#123 Added linux/arm/v7 to build platforms
  .github/workflows/publish-image.yml
Labels: 🎉 feature

#124 Automatically refresh dashboard
  app/Filament/Resources/ResultResource/Pages/ListResults.php
  app/Filament/Widgets/StatsOverview.php
  composer.lock
Labels: 🎉 feature

#130 fix sending data to influxdb
  app/Observers/ResultObserver.php
Labels: 🐛 bug

#137 CI workflow
  .github/workflows/ci.yml
  _ide_helper.php
  app/Observers/ResultObserver.php
  app/Policies/FailedJobPolicy.php
  composer.lock
  tests/Feature/ExampleTest.php
Labels: 🎉 feature

#136 Add jitter data to InfluxDB feed
  app/Models/Result.php
Labels: 🎉 feature

#138 Result created event
  app/Events/ResultCreated.php
  app/Filament/Pages/Settings/InfluxDbPage.php
  app/Filament/Pages/Settings/ThresholdsPage.php
  app/Listeners/Data/InfluxDb2Listener.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteDownloadListener.php
  app/Listeners/Threshold/AbsolutePingListener.php
  app/Listeners/Threshold/AbsoluteUploadListener.php
  app/Models/Result.php
  app/Observers/ResultObserver.php
  app/Providers/EventServiceProvider.php
  app/Settings/ThresholdSettings.php
  database/settings/2022_10_24_153411_create_thresholds_settings.php
Labels: 🎉 feature

#142 Mail notification channel
  app/Filament/Pages/Settings/NotificationPage.php
  app/Forms/Components/TestMailNotification.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteDownloadListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/Listeners/Threshold/AbsolutePingListener.php
  app/Listeners/Threshold/AbsoluteUploadListener.php
  app/Mail/SpeedtestCompletedMail.php
  app/Mail/Test.php
  app/Mail/Threshold/AbsoluteMail.php
  app/Providers/EventServiceProvider.php
  app/Settings/NotificationSettings.php
  app/helpers.php
  database/settings/2022_11_11_134355_create_mail_notification_settings.php
  resources/views/emails/speedtest-completed.blade.php
  resources/views/emails/test.blade.php
  resources/views/emails/threshold/absolute.blade.php
  resources/views/forms/components/test-mail-notification.blade.php
Labels: 🎉 feature

#147 Influxdb data failure
  app/Models/Result.php
Labels: 🐛 bug

#165 Navigation updates
  app/Filament/Pages/Logs.php
  app/Filament/Pages/Settings/InfluxDbPage.php
  app/Filament/Pages/Settings/NotificationPage.php
  app/Providers/FilamentServiceProvider.php
  composer.lock
  config/filament-log.php
Labels: 🐛 bug

#168 made additional metrics nullable in case they're not available
  app/Models/Result.php
Labels: 🐛 bug

#178 Collapsible sidebar nav
  app/Providers/FilamentServiceProvider.php
  config/filament.php
Labels: 🎉 feature

#179 added back filament logs
  app/Providers/FilamentServiceProvider.php
Labels: 🐛 bug

#180 Versions
  .phpstorm.meta.php
  app/Providers/FilamentServiceProvider.php
  composer.json
  composer.lock
Labels: 🎉 feature
