Repository alexjustesen/speedtest-tracker, pull requests merged in 2022-10, with the labels that each got.

#41 Ubuntu 22.04 base image and s6 Overlay v3
  .dockerignore
  .phpstorm.meta.php
  Dockerfile
  _ide_helper.php
  app/helpers.php
  composer.lock
  docker/8.1/php.ini
  docker/deploy/entrypoint.sh
  docker/deploy/etc/s6-overlay/s6-rc.d/cron/run
  docker/deploy/etc/s6-overlay/s6-rc.d/cron/type
  docker/deploy/etc/s6-overlay/s6-rc.d/queue-worker/dependencies
  docker/deploy/etc/s6-overlay/s6-rc.d/queue-worker/run
  docker/deploy/etc/s6-overlay/s6-rc.d/queue-worker/type
  docker/deploy/etc/s6-overlay/s6-rc.d/startup/dependencies
  docker/deploy/etc/s6-overlay/s6-rc.d/startup/type
  docker/deploy/etc/s6-overlay/s6-rc.d/startup/up
  docker/deploy/etc/s6-overlay/s6-rc.d/user/contents.d/queue-worker
  docker/deploy/etc/s6-overlay/s6-rc.d/user/contents.d/startup
  docker/deploy/etc/s6-overlay/scripts/startup
  docker/deploy/etc/services.d/cron/run
  docker/deploy/etc/services.d/queue-worker/run
Labels: 🎉 feature

#49 Report bits not bytes
  Dockerfile
  _ide_helper.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Resources/ResultResource/Pages/ListResults.php
  app/Filament/Resources/ResultResource/Widgets/StatsOverview.php
  app/helpers.php
  composer.lock
  resources/views/tables/columns/bits-column.blade.php
Labels: 🐛 bug

#51 Environment and permission fixes
  .dockerignore
  .env.docker
  .env.example
  .phpstorm.meta.php
  Dockerfile
  _ide_helper.php
  app/Console/Commands/InstallCommand.php
  composer.lock
  database/migrations/2022_10_20_211143_create_sessions_table.php
  docker-compose.yml
  docker/deploy/etc/s6-overlay/scripts/startup
Labels: 🎉 feature

#55 Adhoc speedtest button on dashboard page
  app/Filament/Pages/Dashboard.php
  config/filament.php
  resources/views/filament/pages/dashboard.blade.php
Labels: 🎉 feature

#57 Moved latest test widgets to the dashboard
  app/Filament/Pages/Dashboard.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Resources/ResultResource/Widgets/StatsOverview.php
  app/Filament/Widgets/StatsOverview.php
  app/Providers/FilamentServiceProvider.php
Labels: 🎉 feature

#58 Replace config.yml with settings UI
  .dockerignore
  .gitignore
  .phpstorm.meta.php
  app/Console/Commands/TestInfluxDB.php
  app/Filament/Pages/Dashboard.php
  app/Filament/Pages/Settings/General.php
  app/Filament/Pages/Settings/InfluxDb.php
  app/Jobs/SearchForSpeedtests.php
  app/Observers/ResultObserver.php
  app/Providers/FilamentServiceProvider.php
  app/Settings/GeneralSettings.php
  app/Settings/InfluxDbSettings.php
  composer.json
  composer.lock
  config.example.yml
  config/settings.php
  database/migrations/2022_10_21_104903_create_settings_table.php
  database/settings/2022_10_21_105703_create_general_settings.php
  database/settings/2022_10_21_130121_create_influxdb_settings.php
  docker/deploy/etc/s6-overlay/scripts/startup
Labels: 🎉 feature

#62 Fix cron not running
  docker/deploy/etc/s6-overlay/s6-rc.d/cron/dependencies
  docker/deploy/etc/s6-overlay/s6-rc.d/cron/run
  docker/deploy/etc/s6-overlay/s6-rc.d/cron/type
  docker/deploy/etc/s6-overlay/s6-rc.d/queue-worker/dependencies
  docker/deploy/etc/s6-overlay/s6-rc.d/user/contents.d/cron
Labels: 🐛 bug

#70 When converting bits its to the power of 1000 not 1024
  app/helpers.php
Labels: 🐛 bug

#71 Results time zones, datetime formats and readme improvements
  .github/screenshots/dashboard_screenshot.png
  .github/screenshots/general_settings_screenshot.png
  .github/screenshots/login_screenshot.png
  .github/screenshots/results_screenshot.png
  README.md
  app/Filament/Pages/Settings/General.php
  app/Filament/Resources/ResultResource.php
  app/Settings/GeneralSettings.php
  config/filament.php
  database/settings/2022_10_24_122646_add_time_format_to_general_settings.php
  public/favicon.ico
  public/img/speedtest-tracker-icon.png
  public/vendor/horizon/app-dark.css
  public/vendor/horizon/app.css
  public/vendor/horizon/app.js
  public/vendor/horizon/img/favicon.png
  public/vendor/horizon/img/horizon.svg
  public/vendor/horizon/img/sprite.svg
  public/vendor/horizon/mix-manifest.json
  resources/img/speedtest-tracker-icon.png
Labels: 📖 documentation, 🎉 feature

#68 Setup Dependabot for automatic depdendency updates
  .github/dependabot.yml
Labels: 🎉 feature

#67 Add basic multi-arch build support
  .github/workflows/publish-image.yml
Labels: 🎉 feature

#83 Added database notifications to filament
  config/filament.php
  database/migrations/2022_10_24_152031_create_notifications_table.php
Labels: 🎉 feature

#87 Remove beta tag from Docker image 🎉
  Dockerfile
Labels: 🎉 feature

#85 Performance thresholds
  app/Filament/Pages/Settings/GeneralPage.php
  app/Filament/Pages/Settings/InfluxDbPage.php
  app/Filament/Pages/Settings/NotificationPage.php
  app/Filament/Pages/Settings/ThresholdsPage.php
  app/Forms/Components/TestDatabaseNotification.php
  app/Jobs/SendDataToInfluxDbV2.php
  app/Observers/ResultObserver.php
  app/Settings/NotificationSettings.php
  app/Settings/ThresholdSettings.php
  app/helpers.php
  config/filament.php
  database/settings/2022_10_24_153150_create_database_notifications_settings.php
  database/settings/2022_10_24_153411_create_thresholds_settings.php
  resources/views/filament/forms/notifications-helptext.blade.php
  resources/views/filament/forms/thresholds-helptext.blade.php
  resources/views/forms/components/test-database-notification.blade.php
Labels: 🎉 feature

#88 Disable database notifications by default
  app/Filament/Pages/Settings/InfluxDbPage.php
  database/settings/2022_10_24_153150_create_database_notifications_settings.php
Labels: 🐛 bug

#93 Log viewer
  .phpstorm.meta.php
  app/Providers/FilamentServiceProvider.php
  composer.json
  composer.lock
  config/filament-log.php
  public/vendor/filament-log/css/filament-log.css
  public/vendor/filament-log/mix-manifest.json
Labels: 🎉 feature

#94 Failed jobs viewer
  app/Policies/FailedJobPolicy.php
  app/Providers/AuthServiceProvider.php
  composer.json
  composer.lock
Labels: 🎉 feature
