Repository alexjustesen/speedtest-tracker, pull requests merged in 2023-12, with the labels that each got.

#955 [Bug] use auth helper to correctly set the url
  resources/views/get-started.blade.php
Labels: 🐛 bug

#956 [Bug] Removed should be unique trait from exec speedtest job
  app/Jobs/ExecSpeedtest.php
Labels: 🐛 bug

#960 Laravel 10.35.0 Shift
  _ide_helper.php
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/js/filament/forms/components/file-upload.js
  public/js/filament/forms/components/select.js
  public/js/filament/support/support.js
Labels: 😑 dependencies, 🐘 php

#971 [Chore] Removed delete data page
  app/Filament/Pages/DeleteData.php
  app/Providers/Filament/AdminPanelProvider.php
  resources/views/filament/pages/delete-data.blade.php
Labels: 🧹 chore

#978 [Feature] CLI to update general settings
  app/Console/Commands/UpdateGeneralSettings.php
  app/Helpers/TimeZoneHelper.php
Labels: 🎉 feature

#979 [Feature] Added system checker for local and remote versions
  app/Services/SystemChecker.php
Labels: 🎉 feature

#981 Laravel 10.37.1 Shift
  .phpstorm.meta.php
  _ide_helper.php
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/js/filament/forms/components/color-picker.js
  public/vendor/telescope/app.js
  public/vendor/telescope/mix-manifest.json
Labels: 🧹 chore

#984 [Feature] Database has time zone setting
  app/Filament/Pages/Settings/GeneralPage.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Widgets/RecentJitterChartWidget.php
  app/Filament/Widgets/RecentPingChartWidget.php
  app/Filament/Widgets/RecentSpeedChartWidget.php
  app/Helpers/TimeZoneHelper.php
  app/Http/Controllers/HomeController.php
  app/Settings/GeneralSettings.php
  database/settings/2023_12_12_234839_add_db_has_time_zone_to_general_settings.php
  resources/views/dashboard.blade.php
  resources/views/livewire/debug/timezone.blade.php
Labels: 🎉 feature

#992 [Chore] Removed unused delete data job
  app/Jobs/DeleteResultsData.php
Labels: 🧹 chore

#998 [Bug] Workflow updates
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: 🐛 bug

#996 [MAIL] Send mail with smtp without verifying SSL certificate
  config/mail.php
Labels: 🎉 feature

#994 Laravel 10.38.0 Shift
  _ide_helper.php
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/css/filament/forms/forms.css
  public/js/filament/forms/components/file-upload.js
  public/js/filament/support/async-alpine.js
  public/js/filament/support/support.js
Labels: 🧹 chore

#1002 [Bug] Set x-frame-options header
  app/Http/Middleware/FrameAllowOptions.php
Labels: 🐛 bug

#1003 [Bug] Disable nginx x-frame-options header
  Dockerfile
  docker/deploy/etc/nginx/server-opts.d/security.conf
Labels: 🐛 bug

#1004 Lock PHP image into "serversideup/php" v2.2.1
  Dockerfile
Labels: 🐋 docker

#1005 [Feature] Check for a new version and notify the admin(s)
  app/Console/Commands/VersionChecker.php
  app/Console/Kernel.php
  app/Filament/VersionProviders/SpeedtestTrackerVersionProvider.php
  app/Providers/AppServiceProvider.php
  app/Services/SystemChecker.php
  config/speedtest.php
Labels: 🎉 feature

#1007 [Chore] Refactor running an Ookla speedtest
  app/Console/Commands/RunOoklaSpeedtest.php
  app/Console/Commands/RunSpeedtest.php
  app/Console/Kernel.php
  app/Filament/Pages/Dashboard.php
Labels: 🧹 chore

#1009 [Feature] System maintenance command to keep things healthy
  app/Console/Commands/SystemMaintenance.php
  app/Console/Kernel.php
Labels: 🎉 feature

#1012 Laravel 10.38.2 Shift
  _ide_helper.php
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/css/filament/forms/forms.css
Labels: 🧹 chore

#1014 [Hotfix] v0.14.2-beta2
  app/Services/SystemChecker.php
  config/speedtest.php
Labels: 🐛 bug

#1017 Hotfix v0.14.0 beta3
  app/Filament/VersionProviders/SpeedtestTrackerVersionProvider.php
  app/Services/SystemChecker.php
  config/speedtest.php
Labels: 🐛 bug

#1019 [Bug] added livewire paths to exception list
  app/Http/Middleware/VerifyCsrfToken.php
Labels: 🐛 bug

#1020 [Chore] Upgrade to Vite v5
  package-lock.json
  package.json
  public/build/assets/app-31f612f2.css
  public/build/assets/app-6BD7JOMV.css
  public/build/assets/theme-318e976b.css
  public/build/assets/theme-C5fuYrDC.css
  public/build/manifest.json
  vite.config.js
Labels: 🧹 chore

#1025 [Bug] Removed embeddable public dashboard
  .env.example
  app/Http/Kernel.php
  app/Http/Middleware/FrameAllowOptions.php
  config/speedtest.php
  docker/deploy/etc/nginx/server-opts.d/security.conf
  routes/web.php
Labels: 🐛 bug

#1022 Laravel 10.39.0 Shift
  _ide_helper.php
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/css/filament/forms/forms.css
Labels: 🧹 chore

#1026 [Bug] Removed Livewire csrf exception
  app/Http/Middleware/VerifyCsrfToken.php
Labels: 🐛 bug
