Repository alexjustesen/speedtest-tracker, pull requests merged in 2023-03, with the labels that each got.

#442 Content width setting
  app/Filament/Pages/Dashboard.php
  app/Filament/Pages/Settings/GeneralPage.php
  app/Filament/Pages/Settings/InfluxDbPage.php
  app/Filament/Pages/Settings/NotificationPage.php
  app/Filament/Pages/Settings/ThresholdsPage.php
  app/Filament/Resources/ResultResource/Pages/ListResults.php
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
  app/Settings/GeneralSettings.php
  database/migrations/2022_12_16_164913_transform_speedtest_server_id.php
  database/settings/2023_03_05_233042_add_content_width_to_general_settings.php
Labels: 🎉 feature

#443 InfluxDB verify ssl
  app/Filament/Pages/Settings/InfluxDbPage.php
  app/Jobs/SendDataToInfluxDbV2.php
  app/Settings/InfluxDbSettings.php
  database/settings/2023_03_06_002044_add_verify_ssl_to_influx_db_settings.php
Labels: 🐛 bug

#445 added email validation to the user's email address
  app/Filament/Resources/UserResource.php
Labels: 🐛 bug

#450 [Bugfix] missing general settings class import
  app/Filament/Pages/Settings/ThresholdsPage.php
  config/speedtest.php
Labels: 🐛 bug

#452 s6-overlay improvements
  Dockerfile
  docker-compose.yml
  docker/deploy/cron/scheduler
  docker/deploy/etc/s6-overlay/s6-rc.d/cron/dependencies
  docker/deploy/etc/s6-overlay/s6-rc.d/cron/dependencies.d/laravel-automations
  docker/deploy/etc/s6-overlay/s6-rc.d/cron/run
  docker/deploy/etc/s6-overlay/s6-rc.d/laravel-automations/dependencies
  docker/deploy/etc/s6-overlay/s6-rc.d/queue-worker/dependencies
  docker/deploy/etc/s6-overlay/s6-rc.d/queue-worker/dependencies.d/laravel-automations
  docker/deploy/etc/s6-overlay/s6-rc.d/queue-worker/run
  docker/deploy/etc/s6-overlay/s6-rc.d/startup/dependencies
  docker/deploy/etc/s6-overlay/s6-rc.d/startup/type
  docker/deploy/etc/s6-overlay/s6-rc.d/startup/up
  docker/deploy/etc/s6-overlay/scripts/laravel-automations
  docker/deploy/etc/s6-overlay/scripts/runas-user
Labels: 🎉 feature, 🐋 docker

#458 [Feature] refactored server search and show an initial list
  app/Filament/Pages/Settings/GeneralPage.php
Labels: 🎉 feature

#463 Homepage API support
  app/Http/Controllers/API/Speedtest/GetLatestController.php
  routes/api.php
Labels: 🎉 feature

#464 [Documentation] Initial api documentation
  README.md
  🐇 Speedtest Tracker.postman_collection.json
Labels: 📖 documentation

#468 [Chrore] refactor size conversions
  .phpstorm.meta.php
  _ide_helper.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Widgets/RecentJitterChart.php
  app/Filament/Widgets/RecentPingChart.php
  app/Filament/Widgets/RecentSpeedChart.php
  app/Filament/Widgets/StatsOverview.php
  app/Http/Controllers/API/Speedtest/GetLatestController.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/helpers.php
  composer.json
  composer.lock
Labels: 🧹 Chrore

#472 [Bugfix] fix response when a latest result is not found
  app/Http/Controllers/API/Speedtest/GetLatestController.php
Labels: 🐛 bug

#480 Bugfix: API download speed is reported as upload speed
  app/Http/Controllers/API/Speedtest/GetLatestController.php
Labels: 🐛 bug

#483 [Bugfix] toBits number format
  app/helpers.php
Labels: 🐛 bug

#486 #443 passing verifySSL to the client
  app/Jobs/SendDataToInfluxDbV2.php
  app/Models/Result.php
Labels: 🐛 bug

#494 [Feature] more details in telegram notifications
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  resources/views/telegram/speedtest-completed.blade.php
  resources/views/telegram/threshold/absolute.blade.php
Labels: 🎉 feature

#518 fixing bourne shell syntax error
  docker/deploy/etc/s6-overlay/scripts/laravel-automations
Labels: 🐛 bug
