Repository alexjustesen/speedtest-tracker, pull requests merged in 2023-01, with the labels that each got.

#268 Always format to megabits in recent speed chart
  app/Filament/Widgets/RecentSpeedChart.php
  app/helpers.php
Labels: 🎉 feature

#279 Add cron expression form validation
  app/Filament/Pages/Settings/GeneralPage.php
  app/Rules/ValidCronExpression.php
Labels: 🎉 feature

#287 removed permissions config from docker hub action
  .github/workflows/cd-docker-hub.yml
Labels: 🐛 bug

#289 require recipient email address
  app/Filament/Pages/Settings/NotificationPage.php
Labels: 🐛 bug

#296 added database cache driver support
  database/migrations/2023_01_05_210719_create_cache_table.php
Labels: 🎉 feature

#297 set filament brand config to site name setting
  app/Providers/FilamentServiceProvider.php
  database/migrations/2023_01_05_210719_create_cache_table.php
Labels: 🐛 bug

#299 force https
  .env.example
  app/Providers/AppServiceProvider.php
  config/app.php
Labels: 🎉 feature

#305 Added server_id, server_host and server_name as tags for influxdb
  app/Jobs/SendDataToInfluxDbV2.php
  app/Models/Result.php
Labels: 🎉 feature

#306 User management
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Pages/CreateUser.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
Labels: 🎉 feature

#315 select a manually entered server ID
  app/Filament/Pages/Settings/GeneralPage.php
Labels: 🎉 feature

#265 Telegram notification channel
  app/Filament/Pages/Settings/NotificationPage.php
  app/Forms/Components/TestTelegramNotification.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/Settings/NotificationSettings.php
  app/Telegram/TelegramNotification.php
  composer.json
  composer.lock
  config/services.php
  database/settings/2022_12_22_125055_create_telegram_notification_settings.php
  resources/views/forms/components/test-telegram-notification.blade.php
  resources/views/telegram/speedtest-completed.blade.php
  resources/views/telegram/threshold/absolute.blade.php
Labels: 🎉 feature

#318 Failed speedtests
  .phpstorm.meta.php
  app/Filament/Pages/Dashboard.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Resources/ResultResource/Pages/ListResults.php
  app/Filament/Widgets/RecentJitterChart.php
  app/Filament/Widgets/RecentPingChart.php
  app/Filament/Widgets/RecentSpeedChart.php
  app/Filament/Widgets/StatsOverview.php
  app/Jobs/ExecSpeedtest.php
  app/Models/Result.php
  app/Tables/Columns/BytesColumn.php
  app/Tables/Columns/ServerColumn.php
  app/helpers.php
  composer.lock
  database/migrations/2023_01_12_135235_update_results_table.php
  resources/views/tables/columns/bits-column.blade.php
  resources/views/tables/columns/bytes-column.blade.php
  resources/views/tables/columns/server-column.blade.php
Labels: 🎉 feature

#321 delete speedtest results from the UI
  app/Filament/Pages/DeleteData.php
  app/Filament/Resources/UserResource.php
  app/Jobs/DeleteResultsData.php
  resources/views/filament/pages/delete-data.blade.php
  resources/views/filament/pages/modals/delete-results-data-confirmation.blade.php
Labels: 🎉 feature

#330 Added versioned tag alongside latest on docker-hub deployment
  .github/workflows/cd-docker-hub.yml
Labels: 🎉 feature

#324 Require recipient Telegram and validate bot token
  app/Filament/Pages/Settings/NotificationPage.php
  config/telegram.php
Labels: 🐛 bug

#340 removed auth message
  app/Filament/Pages/Settings/GeneralPage.php
Labels: 📖 documentation

#370 Export selected result records
  app/Exports/ResultsSelectedBulkExport.php
  app/Filament/Resources/ResultResource.php
Labels: 🎉 feature
