Repository alexjustesen/speedtest-tracker, pull requests merged in 2024-10, with the labels that each got.

#1679 [Bug] Remove writing server_id to an column for failed speedtests
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
Labels: 🐛 bug

#1749 Laravel 11.27.2 Shift
  .phpstorm.meta.php
  _ide_helper.php
  app/Actions/MigrateBadJsonResults.php
  app/Actions/Notifications/SendMailTestNotification.php
  app/Filament/Resources/ResultResource.php
  app/Listeners/Data/InfluxDb2Listener.php
  app/Listeners/Database/SendSpeedtestCompletedNotification.php
  app/Listeners/Database/SendSpeedtestThresholdNotification.php
  app/Listeners/Discord/SendSpeedtestCompletedNotification.php
  app/Listeners/Discord/SendSpeedtestThresholdNotification.php
  app/Listeners/Gotify/SendSpeedtestCompletedNotification.php
  app/Listeners/Gotify/SendSpeedtestThresholdNotification.php
  app/Listeners/HealthCheck/SendSpeedtestCompletedNotification.php
  app/Listeners/HealthCheck/SendSpeedtestThresholdNotification.php
  app/Listeners/Mail/SendSpeedtestCompletedNotification.php
  app/Listeners/Mail/SendSpeedtestThresholdNotification.php
  app/Listeners/Ntfy/SendSpeedtestCompletedNotification.php
  app/Listeners/Ntfy/SendSpeedtestThresholdNotification.php
  app/Listeners/Pushover/SendSpeedtestCompletedNotification.php
  app/Listeners/Pushover/SendSpeedtestThresholdNotification.php
  app/Listeners/Slack/SendSpeedtestCompletedNotification.php
  app/Listeners/Slack/SendSpeedtestThresholdNotification.php
  app/Listeners/Telegram/SendSpeedtestCompletedNotification.php
  app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
  app/Listeners/Webhook/SendSpeedtestCompletedNotification.php
  app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
  app/Notifications/Telegram/TestNotification.php
  app/Providers/Filament/AdminPanelProvider.php
  composer.json
  composer.lock
  database/migrations/2024_02_18_100000_results_bad_json_table.php
  database/migrations/2024_02_19_134706_create_imports_table.php
  database/migrations/2024_02_19_134707_create_exports_table.php
  database/migrations/2024_02_19_134708_create_failed_import_rows_table.php
  public/css/filament/filament/app.css
  public/css/filament/forms/forms.css
  public/js/filament/forms/components/file-upload.js
  public/js/filament/forms/components/markdown-editor.js
  public/js/filament/support/support.js
Labels: 🧹 chore

#1746 [Chore] improve composer.json
  composer.json
Labels: 🧹 chore

#1755 Hotfix v0.21.4
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
  config/speedtest.php
Labels: 🐛 bug

#1759 Update README.md
  README.md
Labels: 📖 documentation
