Repository alexjustesen/speedtest-tracker, pull requests merged in 2024-02, with the labels that each got.

#1079 Laravel 10.43.0 Shift
  .phpstorm.meta.php
  _ide_helper.php
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/js/filament/forms/components/color-picker.js
  public/js/filament/forms/components/file-upload.js
  public/js/filament/forms/components/markdown-editor.js
  public/js/filament/support/support.js
  public/js/filament/tables/components/table.js
Labels: 🧹 chore

#1083 [Chore] specified platform php version
  composer.json
Labels: 🧹 chore

#1084 [Bug] Change default cache driver to database
  .env.testing
  config/cache.php
Labels: 🐛 bug

#1093 [Bug] Removed initial cache clear on startup
  docker/deploy/etc/s6-overlay/scripts/laravel-automations
Labels: 🐛 bug

#1097 [Bug] Wrap system maintenance commands in try to soft fail the command
  app/Console/Commands/SystemMaintenance.php
Labels: 🐛 bug

#1100 [Chore] Added one time operations package
  _ide_helper.php
  composer.json
  composer.lock
Labels: 🧹 chore

#754 feat: add webhook notifications
  app/Filament/Pages/Settings/NotificationPage.php
  app/Forms/Components/TestWebhookNotification.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/Settings/NotificationSettings.php
  database/migrations/2023_09_11_144858_create_webhook_notification_settings.php
  resources/views/forms/components/test-webhook-notification.blade.php
Labels: 🎉 feature

#1103 [Feature] Add webhook notifications
  app/Filament/Pages/Settings/NotificationPage.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/Settings/NotificationSettings.php
  composer.json
  composer.lock
  config/webhook-server.php
  database/migrations/2023_09_11_144858_create_webhook_notification_settings.php
Labels: 🎉 feature

#1104 [Chore] Refactor notification channel tests
  .phpstorm.meta.php
  _ide_helper.php
  app/Actions/Notifications/SendDatabaseTestNotification.php
  app/Actions/Notifications/SendMailTestNotification.php
  app/Actions/Notifications/SendTelegramTestNotification.php
  app/Actions/Notifications/SendWebhookTestNotification.php
  app/Filament/Pages/Settings/NotificationPage.php
  app/Forms/Components/TestDatabaseNotification.php
  app/Forms/Components/TestMailNotification.php
  app/Forms/Components/TestTelegramNotification.php
  composer.json
  composer.lock
  resources/views/forms/components/test-database-notification.blade.php
  resources/views/forms/components/test-mail-notification.blade.php
  resources/views/forms/components/test-telegram-notification.blade.php
Labels: 🧹 chore

#1105 [Chore] Refactored get jitter data method
  app/Models/Result.php
Labels: 🧹 chore

#1109 [Chore] Refactored getting Ookla speedtest servers
  app/Actions/GetOoklaSpeedtestServers.php
  app/Filament/Pages/Settings/GeneralPage.php
Labels: 🧹 chore

#1070 [Bug] Timezone in API returns
  app/Http/Controllers/API/Speedtest/GetLatestController.php
Labels: 🐛 bug

#1110 [Feature] Silently send notifications for Telegram
  app/Filament/Pages/Settings/NotificationPage.php
  app/Settings/NotificationSettings.php
  database/settings/2024_02_07_173217_add_telegram_disable_notification_to_notification_settings.php
Labels: 🎉 feature

#1114 Release v0.15.2 (Hotfix)
  app/Console/Commands/SystemMaintenance.php
  config/speedtest.php
Labels: 🐛 bug

#1124 [Feature] A better favicon
  app/Providers/Filament/AdminPanelProvider.php
  public/favicon.ico
  public/img/speedtest-tracker-icon.png
  resources/views/layouts/app.blade.php
  resources/views/layouts/debug.blade.php
Labels: 🎉 feature

#1139 [Chore] README.md and template updates
  .github/pull_request_template.md
  .github/screenshots/general_settings_screenshot.jpg
  .github/screenshots/login_screenshot.jpg
  .github/screenshots/results_screenshot.jpg
  README.md
Labels: 🧹 chore

#812 [Bug] Fix incorrectly formatted json data
  app/Actions/MigrateBadJsonResults.php
  app/Enums/ResultStatus.php
  app/Exports/ResultsSelectedBulkExport.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Widgets/RecentJitterChartWidget.php
  app/Filament/Widgets/RecentPingChartWidget.php
  app/Filament/Widgets/RecentSpeedChartWidget.php
  app/Filament/Widgets/StatsOverviewWidget.php
  app/Http/Controllers/API/Speedtest/GetLatestController.php
  app/Http/Controllers/HomeController.php
  app/Jobs/ExecSpeedtest.php
  app/Models/Result.php
  app/Settings/DataMigrationSettings.php
  database/migrations/2024_02_18_100000_results_bad_json_table.php
  database/settings/2024_02_18_000000_create_data_migration_settings.php
Labels: 🐛 bug

#1144 [Feature] Automatically prune results
  app/Console/Kernel.php
  app/Filament/Pages/Settings/GeneralPage.php
  app/Models/Result.php
  app/Settings/GeneralSettings.php
  database/settings/2024_02_19_022251_add_prune_results_to_general_settings.php
Labels: 🎉 feature

#1145 [Bug] Fixed missing version provider namespace
  app/Filament/VersionProviders/SpeedtestTrackerVersionProvider.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: 🐛 bug

#1146 [Chore] Cache settings values
  config/settings.php
Labels: 🧹 chore

#1149 [Feature] Use Filament resource exporter
  .phpstorm.meta.php
  _ide_helper.php
  app/Exports/ResultsSelectedBulkExport.php
  app/Filament/Exports/ResultExporter.php
  app/Filament/Resources/ResultResource.php
  composer.json
  composer.lock
  database/migrations/2024_02_19_134641_create_job_batches_table.php
  database/migrations/2024_02_19_134706_create_imports_table.php
  database/migrations/2024_02_19_134707_create_exports_table.php
  database/migrations/2024_02_19_134708_create_failed_import_rows_table.php
Labels: 🎉 feature

#1150 [Bug] Correctly format failed speedtests
  app/Filament/Resources/ResultResource.php
  app/Jobs/ExecSpeedtest.php
  app/Models/Result.php
Labels: 🐛 bug

#1160 [Bug] Wrong results value
  app/Filament/Exports/ResultExporter.php
  app/Filament/Resources/ResultResource.php
Labels: 🐛 bug

#1170 [Bug] Download and upload bits should be a nullable int
  app/Models/Result.php
Labels: 🐛 bug

#1172 [Bug] Don't select null external IP addresses
  app/Filament/Resources/ResultResource.php
Labels: 🐛 bug

#1181 [Bug] Capture 1 or true for successful status
  app/Actions/MigrateBadJsonResults.php
Labels: 🐛 bug

#1182 [Bug] Fixed incorrect file size bits calculation
  app/Filament/Resources/ResultResource.php
  app/Helpers/Number.php
Labels: 🐛 bug

#1198 [Bug] Fixed charts query not ordering by latest
  app/Filament/Widgets/RecentJitterChartWidget.php
  app/Filament/Widgets/RecentPingChartWidget.php
  app/Filament/Widgets/RecentSpeedChartWidget.php
Labels: 🐛 bug

#1199 [Chore] Bit number helpers
  app/Filament/Resources/ResultResource.php
  app/Filament/Widgets/StatsOverviewWidget.php
  app/Helpers/Number.php
Labels: 🧹 chore

#1200 [Feature] Added bit to magnitude helper
  app/Helpers/Number.php
Labels: 🎉 feature

#1201 [Bug] Return latest speedtest download and upload in mbits
  app/Helpers/Number.php
  app/Http/Controllers/API/Speedtest/GetLatestController.php
  routes/api.php
Labels: 🐛 bug

#1212 Laravel 10.45.1 Shift
  _ide_helper.php
  composer.json
  composer.lock
Labels: 🧹 chore

#1218 [Bug] Added default download and upload value when assessing if a threshold was breached
  app/helpers.php
Labels: 🐛 bug

#1196 [Feature] Discord Webhook Functionality
  app/Actions/Notifications/SendDiscordTestNotification.php
  app/Filament/Pages/Settings/NotificationPage.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/Settings/NotificationSettings.php
  database/migrations/2024_02_19_000000_create_discord_notification_settings.php
Labels: 🎉 feature

#1219 [Chore] Fixed location of setting migrations
  app/Actions/Notifications/SendDiscordTestNotification.php
  database/settings/2023_09_11_144858_create_webhook_notification_settings.php
  database/settings/2024_02_22_144650_create_discord_notification_settings.php
Labels: 🧹 chore

#1221 [CHore] Refactored discord webhooks to use WebhookCall
  app/Actions/Notifications/SendDiscordTestNotification.php
  app/Actions/Notifications/SendWebhookTestNotification.php
  app/Filament/Pages/Settings/NotificationPage.php
Labels: 🧹 chore

#1230 [Feature] Added heathcheck API route
  app/Http/Controllers/API/HealthCheckController.php
  routes/api.php
Labels: 🎉 feature

#1231 [Bug] Dixed missing server host reference
  app/Filament/Resources/ResultResource.php
Labels: 🐛 bug

#1236 Hotfix v0.17.2
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  config/speedtest.php
Labels: 🐛 bug

#1242 [Chore] Refactored Discord notifications to use WebhookCall
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
Labels: 🧹 chore

#1251 [Bug] Fixed sortable query for json data
  app/Filament/Resources/ResultResource.php
Labels: 🐛 bug

#1262 [Bug] Fixed view created at timezone
  app/Filament/Resources/ResultResource.php
Labels: 🐛 bug

#1264 [Chore] Refactored executing Ookla speedtests and added new events
  app/Actions/Speedtests/RunOoklaSpeedtest.php
  app/Actions/Speedtests/RunScheduledSpeedtests.php
  app/Console/Commands/RunOoklaSpeedtest.php
  app/Console/Kernel.php
  app/Events/ResultCreated.php
  app/Events/SpeedtestCompleted.php
  app/Events/SpeedtestFailed.php
  app/Events/SpeedtestStarted.php
  app/Filament/Pages/Dashboard.php
  app/Jobs/ExecSpeedtest.php
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
  app/Listeners/Data/InfluxDb2Listener.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/Models/Result.php
  app/Providers/EventServiceProvider.php
Labels: 🧹 chore

#1266 [Chore] Refactored database notifications to their own listeners
  app/Listeners/Database/SendSpeedtestCompletedNotification.php
  app/Listeners/Database/SendSpeedtestThresholdNotification.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/Providers/EventServiceProvider.php
Labels: 🧹 chore

#1267 [Chore] Refactored webhook notifications to their own listeners
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/Listeners/Webhook/SendSpeedtestCompletedNotification.php
  app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
  app/Providers/EventServiceProvider.php
Labels: 🧹 chore
