Repository alexjustesen/speedtest-tracker, pull requests merged in 2024-04, with the labels that each got.

#1339 [Bug] Use can access method for pages
  app/Filament/Pages/Dashboard.php
  app/Filament/Pages/Settings/GeneralPage.php
  app/Filament/Pages/Settings/InfluxDbPage.php
  app/Filament/Pages/Settings/NotificationPage.php
  app/Filament/Pages/Settings/ThresholdsPage.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Resources/UserResource.php
Labels: 🐛 bug

#1340 [Bug] Divide by zero
  app/Helpers/Number.php
  app/helpers.php
Labels: 🐛 bug

#1353 Add upload and download latency information
  app/Filament/Exports/ResultExporter.php
  app/Filament/Pages/Dashboard.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
  app/Filament/Widgets/RecentUploadLatencyChartWidget.php
  app/Models/Result.php
Labels: 🎉 feature

#1362 [Feature] Added ability to truncate the results table
  app/Filament/Resources/ResultResource.php
  app/Jobs/TruncateResults.php
Labels: 🎉 feature

#1361 Laravel 10.48.5 Shift
  _ide_helper.php
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/js/filament/notifications/notifications.js
  public/js/filament/support/support.js
Labels: 🧹 chore

#1363 [Chore] Badges labels and color updates
  app/Enums/ResultStatus.php
  app/Enums/UserRole.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Resources/UserResource.php
  app/Models/User.php
Labels: 🧹 chore

#1377 [Bug] Added timezone to latest speedtest API response
  app/Http/Controllers/API/Speedtest/GetLatestController.php
Labels: 🐛 bug

#1380 [Chore] Added deprecated image warning to admin panel
  Dockerfile
  app/Filament/Pages/Dashboard.php
  app/Filament/Widgets/DeprecatedImage.php
  resources/views/filament/widgets/deprecated-image.blade.php
Labels: 🧹 chore

#1384 Add Packet loss to CSV export
  app/Filament/Exports/ResultExporter.php
Labels: 🎉 feature

#1385 [Chore] Upgraded sail development environment to PHP 8.3
  .github/workflows/tests.yml
  composer.json
  docker-compose.yml
  docker/8.2/start-container
  docker/8.3/Dockerfile
  docker/8.3/php.ini
  docker/8.3/start-container
  docker/8.3/supervisord.conf
Labels: 🧹 chore

#1390 Add App url and Packet loss to the notifications
  app/Listeners/Discord/SendSpeedtestCompletedNotification.php
  app/Listeners/Discord/SendSpeedtestThresholdNotification.php
  app/Listeners/Telegram/SendSpeedtestCompletedNotification.php
  app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
  app/Listeners/Webhook/SendSpeedtestCompletedNotification.php
  app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
  app/Mail/SpeedtestCompletedMail.php
  resources/views/discord/speedtest-completed.blade.php
  resources/views/discord/speedtest-threshold.blade.php
  resources/views/emails/speedtest-completed.blade.php
  resources/views/telegram/speedtest-completed.blade.php
  resources/views/telegram/speedtest-threshold.blade.php
Labels: 🎉 feature
