Repository alexjustesen/speedtest-tracker, pull requests merged in 2024-12, with the labels that each got.

#1865 [Feature] Change Average to solid line & Add grace
  app/Filament/Widgets/RecentDownloadChartWidget.php
  app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
  app/Filament/Widgets/RecentPingChartWidget.php
  app/Filament/Widgets/RecentUploadChartWidget.php
  app/Filament/Widgets/RecentUploadLatencyChartWidget.php
Labels: 🎉 feature

#1867 [Chore] Don't track ide helpers
  .gitignore
  .phpstorm.meta.php
  _ide_helper.php
Labels: 🧹 chore

#1868 [Chore] Removed ide helper
  composer.json
  composer.lock
Labels: 🧹 chore

#1866 [Feature] Refactor InfluxDB integration + add bulk import results (⚠️ breaking change)
  app/Actions/Influxdb/v2/BuildPointData.php
  app/Actions/Influxdb/v2/CreateClient.php
  app/Console/Commands/TestInfluxDB.php
  app/Enums/ResultService.php
  app/Filament/Pages/Settings/DataIntegrationPage.php
  app/Filament/Pages/Settings/InfluxDbPage.php
  app/Jobs/InfluxDBv2/WriteCompletedSpeedtest.php
  app/Jobs/Influxdb/v2/BulkWriteResults.php
  app/Jobs/Influxdb/v2/TestConnectionJob.php
  app/Jobs/Influxdb/v2/WriteResult.php
  app/Listeners/Data/InfluxDb2Listener.php
  app/Listeners/SpeedtestEventSubscriber.php
  app/Models/Result.php
  app/Models/Traits/ResultDataAttributes.php
  app/Settings/DataIntegrationSettings.php
  app/Settings/InfluxDbSettings.php
  database/factories/ResultFactory.php
  database/settings/2024_09_11_094357_rename_influxdb_settings.php.php
Labels: 🎉 feature

#1880 [Bug] Cast Influxdb point values
  app/Actions/Influxdb/v2/BuildPointData.php
  app/Helpers/Number.php
Labels: 🐛 bug

#1884 [Feature] Add App Name to notifications
  resources/views/discord/speedtest-completed.blade.php
  resources/views/discord/speedtest-threshold.blade.php
  resources/views/gotify/speedtest-completed.blade.php
  resources/views/gotify/speedtest-threshold.blade.php
  resources/views/ntfy/speedtest-completed.blade.php
  resources/views/ntfy/speedtest-threshold.blade.php
  resources/views/pushover/speedtest-completed.blade.php
  resources/views/pushover/speedtest-threshold.blade.php
  resources/views/slack/speedtest-completed.blade.php
  resources/views/slack/speedtest-threshold.blade.php
  resources/views/telegram/speedtest-completed.blade.php
  resources/views/telegram/speedtest-threshold.blade.php
Labels: 🎉 feature

#1892 [Bug] Don't use factory to test influxdb connection
  app/Jobs/Influxdb/v2/TestConnectionJob.php
Labels: 🐛 bug

#1902 [Bug] Fixed dockerfile build steps for better caching
  docker/8.3/Dockerfile
Labels: 🐛 bug

#1896 [Feature] Implement a blocked servers list
  app/Jobs/Ookla/SelectSpeedtestServerJob.php
  config/speedtest.php
Labels: 🎉 feature

#1908 [Chore] Update policies to use Illuminate\Auth\Access\Response
  app/Policies/ResultPolicy.php
  app/Policies/UserPolicy.php
Labels: 🧹 chore

#1906 Laravel 11.35.0 Shift
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/css/filament/forms/forms.css
  public/js/filament/filament/echo.js
  public/js/filament/forms/components/file-upload.js
  public/js/filament/forms/components/rich-editor.js
  public/js/filament/support/support.js
  public/js/filament/tables/tables.js
Labels: 🧹 chore

#1911 [Chore] Removed bad json functions and squashed migrations
  app/Actions/MigrateBadJsonResults.php
  app/Filament/Resources/ResultResource.php
  app/Settings/DataMigrationSettings.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2022_08_31_202106_create_results_table.php
  database/migrations/2022_09_27_212959_create_admin_user.php
  database/migrations/2023_01_12_135235_update_results_table.php
  database/migrations/2023_02_12_131620_add_comments_to_results_table.php
  database/migrations/2023_09_11_225054_add_role_to_users_table.php
  database/migrations/2024_02_18_100000_results_bad_json_table.php
  database/settings/2024_02_18_000000_create_data_migration_settings.php
Labels: 🧹 chore

#1914 [Documentation] Updated docs for v1
  .github/screenshots/dashboard.jpeg
  .github/screenshots/dashboard_screenshot.jpg
  README.md
  SECURITY.md
  🐇 Speedtest Tracker.postman_collection.json
Labels: 📖 documentation

#1929 [Bug] Fix logic to check for existing server ID in SelectSpeedtestServerJob
  app/Jobs/Ookla/SelectSpeedtestServerJob.php
Labels: 🐛 bug

#1951 [Feature] Added custom "blank" and "filled" Blade directives
  app/Providers/AppServiceProvider.php
Labels: 🎉 feature

#1952 [Feature] Implement middleware to prevent overlapping execution of "RunSpeedtestJob"
  app/Jobs/Ookla/RunSpeedtestJob.php
Labels: 🎉 feature

#1958 [Chore] Add logging configuration file and set stderr as the default
  config/logging.php
Labels: 🧹 chore
