Repository alexjustesen/speedtest-tracker, pull requests merged in 2024-07, with the labels that each got.

#1614 [Bug] Default server id to null when executing speedtest
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
Labels: 🐛 bug

#1608 Laravel 11.16.0 Shift
  _ide_helper.php
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/vendor/telescope/app.js
  public/vendor/telescope/mix-manifest.json
Labels: 🧹 chore

#1579 Add ntfy Notifications via Webhooks
  app/Actions/Notifications/SendNtfyTestNotification.php
  app/Filament/Pages/Settings/NotificationPage.php
  app/Listeners/Ntfy/SendSpeedtestCompletedNotification.php
  app/Listeners/Ntfy/SendSpeedtestThresholdNotification.php
  app/Settings/NotificationSettings.php
  database/settings/2024_02_22_144650_create_ntfy_notification_settings.php
  resources/views/ntfy/speedtest-completed.blade.php
  resources/views/ntfy/speedtest-threshold.blade.php
Labels: 🎉 feature

#1615 Add Ookla URL to the notification
  app/Listeners/Discord/SendSpeedtestCompletedNotification.php
  app/Listeners/Discord/SendSpeedtestThresholdNotification.php
  app/Listeners/Gotify/SendSpeedtestCompletedNotification.php
  app/Listeners/Gotify/SendSpeedtestThresholdNotification.php
  app/Listeners/HealthCheck/SendSpeedtestCompletedNotification.php
  app/Listeners/HealthCheck/SendSpeedtestThresholdNotification.php
  app/Listeners/Ntfy/SendSpeedtestCompletedNotification.php
  app/Listeners/Ntfy/SendSpeedtestThresholdNotification.php
  app/Listeners/Pushover/SendSpeedtestCompletedNotification.php
  app/Listeners/Pushover/SendSpeedtestThresholdNotification.php
  app/Listeners/Slack/SendSpeedtestCompletedNotification.php
  app/Listeners/Slack/SendSpeedtestThresholdNotification.php
  app/Listeners/Telegram/SendSpeedtestCompletedNotification.php
  app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
  app/Listeners/Webhook/SendSpeedtestCompletedNotification.php
  app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
  app/Mail/SpeedtestCompletedMail.php
  app/Mail/SpeedtestThresholdMail.php
  resources/views/discord/speedtest-completed.blade.php
  resources/views/discord/speedtest-threshold.blade.php
  resources/views/emails/speedtest-completed.blade.php
  resources/views/emails/speedtest-threshold.blade.php
  resources/views/gotify/speedtest-completed.blade.php
  resources/views/gotify/speedtest-threshold.blade.php
  resources/views/ntfy/speedtest-completed.blade.php
  resources/views/ntfy/speedtest-threshold.blade.php
  resources/views/pushover/speedtest-completed.blade.php
  resources/views/pushover/speedtest-threshold.blade.php
  resources/views/slack/speedtest-completed.blade.php
  resources/views/telegram/speedtest-completed.blade.php
  resources/views/telegram/speedtest-threshold.blade.php
Labels: 🎉 feature

#1628 Laravel 11.18.1 Shift
  _ide_helper.php
  composer.json
  composer.lock
  public/js/filament/widgets/components/stats-overview/stat/chart.js
Labels: 🧹 chore
