Repository alexjustesen/speedtest-tracker, pull requests merged in 2024-11, with the labels that each got.

#1732 Improvements user resource
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
Labels: 🧹 chore

#1783 [Chore] Refactor user resource
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
Labels: 🧹 chore

#1771 Laravel 11.30.0 Shift
  _ide_helper.php
  composer.json
  composer.lock
  docker/8.3/Dockerfile
  docker/mariadb/create-testing-database.sh
  public/js/filament/forms/components/file-upload.js
  public/vendor/telescope/app.js
  public/vendor/telescope/mix-manifest.json
Labels: 🧹 chore

#1754 Fix ping url validation
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
  tests/Unit/ExampleTest.php
  tests/Unit/ExecuteOoklaSpeedtestTest.php
Labels: 🐛 bug

#1714 [Feature] Skip test when Public IP is in an list
  app/Enums/ResultStatus.php
  app/Events/SpeedtestSkipped.php
  app/Filament/Resources/ResultResource.php
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
  app/Services/PublicIpService.php
  config/speedtest.php
Labels: 🎉 feature

#1795 [Feature] Skip test when Public IP is in a list (#1714)
  app/Actions/Helpers/GetExternalIpAddress.php
  app/Enums/ResultStatus.php
  app/Events/SpeedtestSkipped.php
  app/Filament/Resources/ResultResource.php
  app/Helpers/Network.php
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
  config/speedtest.php
Labels: 🎉 feature

#1712 [Feature] Add markdown content type for gotify notification
  app/Listeners/Gotify/SendSpeedtestCompletedNotification.php
  app/Listeners/Gotify/SendSpeedtestThresholdNotification.php
  resources/views/gotify/speedtest-completed.blade.php
  resources/views/gotify/speedtest-threshold.blade.php
Labels: 🎉 feature

#1800 [Chore] Cleaned up enums
  app/Enums/ResultStatus.php
  app/Enums/UserRole.php
Labels: 🧹 chore

#1801 [Feature] Added result url to export
  app/Filament/Exports/ResultExporter.php
Labels: 🎉 feature

#1803 [Chore] Only skip scheduled tests
  app/Actions/Speedtests/RunOoklaSpeedtest.php
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
Labels: 🧹 chore

#1763 [Feature] Server selection for manual tests
  app/Actions/GetOoklaSpeedtestServers.php
  app/Filament/Pages/Dashboard.php
Labels: 🎉 feature

#1805 [Bug] Added server id to start speedtest action
  app/Actions/Ookla/StartSpeedtest.php
  app/Filament/Pages/Dashboard.php
Labels: 🐛 bug

#1809 [Bug] Fixed service enum label
  app/Listeners/Discord/SendSpeedtestCompletedNotification.php
  app/Listeners/Discord/SendSpeedtestThresholdNotification.php
  app/Listeners/Gotify/SendSpeedtestCompletedNotification.php
  app/Listeners/Gotify/SendSpeedtestThresholdNotification.php
  app/Listeners/Ntfy/SendSpeedtestCompletedNotification.php
  app/Listeners/Ntfy/SendSpeedtestThresholdNotification.php
  app/Listeners/Pushover/SendSpeedtestCompletedNotification.php
  app/Listeners/Pushover/SendSpeedtestThresholdNotification.php
  app/Listeners/Slack/SendSpeedtestCompletedNotification.php
  app/Listeners/Slack/SendSpeedtestThresholdNotification.php
  app/Listeners/Telegram/SendSpeedtestCompletedNotification.php
  app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
  app/Mail/SpeedtestCompletedMail.php
  app/Mail/SpeedtestThresholdMail.php
Labels: 🐛 bug

#1812 [Feature] Added result checking and running statuses
  app/Enums/ResultStatus.php
  app/Events/SpeedtestChecking.php
  app/Events/SpeedtestRunning.php
  app/Jobs/CheckForInternetConnectionJob.php
  app/Jobs/Ookla/RunSpeedtestJob.php
Labels: 🎉 feature

#1813 [Feature] Added benchmarks to results table
  app/Enums/ResultStatus.php
  app/Events/SpeedtestBenchmarking.php
  app/Jobs/Ookla/BenchmarkSpeedtestJob.php
  app/Jobs/Ookla/CompleteSpeedtestJob.php
  app/Jobs/Ookla/ProcessSpeedtestBatch.php
  app/Jobs/Ookla/RunSpeedtestJob.php
  app/Models/Result.php
  database/migrations/2024_11_22_235011_add_benchmarks_to_results_table.php
Labels: 🎉 feature

#1814 [Feature] Added healthy indicator to results
  app/Actions/Ookla/EvaluateResultHealth.php
  app/Helpers/Benchmark.php
  app/Helpers/Bitrate.php
  app/Jobs/Ookla/BenchmarkSpeedtestJob.php
  app/Models/Result.php
  database/migrations/2024_11_23_021744_add_healthy_to_results_table.php
Labels: 🎉 feature

#1820 [Feature] Added defined config servers to dropdown
  app/Filament/Pages/Dashboard.php
  app/Helpers/Ookla.php
  config/speedtest.php
Labels: 🎉 feature

#1826 [Bug] Capture curl errors when offline
  app/Actions/GetExternalIpAddress.php
  app/Actions/GetOoklaSpeedtestServers.php
  app/Filament/Pages/Dashboard.php
Labels: 🐛 bug

#1827 [Bug] Fixed high ping values not showing in charts
  app/Filament/Widgets/RecentPingChartWidget.php
Labels: 🐛 bug

#1832 [Bug] High values not showing in charts
  app/Filament/Widgets/RecentDownloadChartWidget.php
  app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
  app/Filament/Widgets/RecentJitterChartWidget.php
  app/Filament/Widgets/RecentUploadChartWidget.php
  app/Filament/Widgets/RecentUploadLatencyChartWidget.php
Labels: 🐛 bug

#1831 [Feature] Added select speedtest server job
  app/Actions/Ookla/SelectSpeedtestServer.php
  app/Actions/Ookla/StartSpeedtest.php
  app/Jobs/Ookla/ProcessSpeedtestBatch.php
  app/Jobs/Ookla/SelectSpeedtestServerJob.php
Labels: 🎉 feature

#1816 [Feature] Added Check benchmark for healthy
  app/Filament/Resources/ResultResource.php
  app/Jobs/CheckAndUpdateBenchmarkResult.php
  app/Jobs/Ookla/ProcessSpeedtestBatch.php
Labels: 🎉 feature

#1842 [Feature] Added dashboard buttons to the toolbar
  app/Filament/Pages/Dashboard.php
  app/Livewire/Topbar/RunSpeedtestAction.php
  app/Providers/FilamentServiceProvider.php
  bootstrap/providers.php
  public/css/app/panel.css
  resources/css/panel.css
  resources/views/livewire/topbar/run-speedtest-action.blade.php
Labels: 🎉 feature

#1835 [Chore] Refactored benchmarking results
  app/Actions/Ookla/EvaluateResultHealth.php
  app/Filament/Resources/ResultResource.php
  app/Helpers/Benchmark.php
  app/Jobs/Ookla/BenchmarkSpeedtestJob.php
  app/Jobs/Ookla/ProcessSpeedtestBatch.php
  app/Jobs/Ookla/SkipSpeedtestJob.php
Labels: 🧹 chore

#1839 [Feature] Fill charts with 10% and make beginAtZero configurable
  app/Filament/Widgets/RecentDownloadChartWidget.php
  app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
  app/Filament/Widgets/RecentJitterChartWidget.php
  app/Filament/Widgets/RecentPingChartWidget.php
  app/Filament/Widgets/RecentUploadChartWidget.php
  app/Filament/Widgets/RecentUploadLatencyChartWidget.php
  config/app.php
Labels: 🎉 feature
