Repository alexjustesen/speedtest-tracker, pull requests merged in 2024-06, with the labels that each got.

#1457 [Bug] removed extra $ in password reset error message
  app/Console/Commands/ResetUserPassword.php
Labels: 🐛 bug

#1458 Refactor app commands
  app/Console/Commands/InstallCommand.php
  app/Console/Commands/ResetUserPassword.php
  app/Console/Commands/ResultFixStatuses.php
  app/Console/Commands/SystemMaintenance.php
  app/Console/Commands/UpdateGeneralSettings.php
  app/Console/Commands/UserChangeRole.php
  app/Console/Commands/UserResetPassword.php
  app/Console/Commands/VersionChecker.php
  bootstrap/app.php
Labels: 🧹 chore

#1456 Laravel 11.10.0 Shift
  _ide_helper.php
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/js/filament/forms/components/key-value.js
  public/js/filament/notifications/notifications.js
Labels: 🧹 chore

#1459 [Chore] Use Cloudflare instead of google for internet checks
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
Labels: 🧹 chore

#1445 [Feature] Refactored container startup process (BREAKING CHANGE)
  .env.production
  config/app.php
  config/services.php
  config/speedtest.php
  docker/deploy/etc/s6-overlay/scripts/laravel-automations
Labels: 🎉 feature

#1462 [Chore] Use SQLite for development env
  .env.example
  docker-compose.yml
Labels: 🧹 chore

#1464 [Feature] Removed general settings page (BREAKING CHANGE)
  .phpstorm.meta.php
  _ide_helper.php
  app/Actions/Speedtests/RunScheduledSpeedtests.php
  app/Console/Commands/OoklaListServers.php
  app/Console/Commands/ResultFixStatuses.php
  app/Console/Commands/UpdateGeneralSettings.php
  app/Filament/Pages/Dashboard.php
  app/Filament/Pages/Settings/GeneralPage.php
  app/Filament/Resources/ResultResource.php
  app/Filament/Resources/UserResource.php
  app/Filament/Widgets/RecentDownloadChartWidget.php
  app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
  app/Filament/Widgets/RecentJitterChartWidget.php
  app/Filament/Widgets/RecentPingChartWidget.php
  app/Filament/Widgets/RecentUploadChartWidget.php
  app/Filament/Widgets/RecentUploadLatencyChartWidget.php
  app/Helpers/TimeZoneHelper.php
  app/Http/Controllers/API/Speedtest/GetLatestController.php
  app/Http/Controllers/HomeController.php
  app/Livewire/Debug/Timezone.php
  app/Models/Result.php
  app/Settings/GeneralSettings.php
  bootstrap/app.php
  composer.json
  config/app.php
  config/speedtest.php
  database/migrations/2022_12_16_164913_transform_speedtest_server_id.php
  database/migrations/2024_02_18_100000_results_bad_json_table.php
  database/settings/2022_10_21_105703_create_general_settings.php
  database/settings/2022_10_24_122646_add_time_format_to_general_settings.php
  database/settings/2023_03_05_233042_add_content_width_to_general_settings.php
  database/settings/2023_10_07_113220_add_public_dashboard_enabled_to_general_settings.php
  database/settings/2023_12_12_234839_add_db_has_time_zone_to_general_settings.php
  database/settings/2024_02_18_010000_add_prune_results_to_general_settings.php
  resources/views/dashboard.blade.php
  resources/views/livewire/debug/timezone.blade.php
  routes/console.php
Labels: 🎉 feature

#1465 [Chore] Removed bundled assets
  .gitignore
  public/build/assets/app-zAziKUDq.css
  public/build/assets/theme-BgC2MXSU.css
  public/build/manifest.json
Labels: 🧹 chore

#1466 [Feature] added filament user profile
  app/Filament/Resources/UserResource.php
  app/Providers/Filament/AdminPanelProvider.php
Labels: 🎉 feature

#1468 [Docs] updated generate app key url
  README.md
Labels: 📖 documentation

#1471 [Bug] Default display timezone to utc
  config/app.php
Labels: 🐛 bug

#1472 [Bug] Display timezone should be used for scheduled tests
  app/Actions/Speedtests/RunScheduledSpeedtests.php
Labels: 🐛 bug

#1477 [Feature] Display next speedtest run at date on dashboard
  app/Filament/Pages/Dashboard.php
Labels: 🎉 feature

#1480 [Feature] Added chart datetime format environment variable
  app/Filament/Widgets/RecentDownloadChartWidget.php
  app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
  app/Filament/Widgets/RecentJitterChartWidget.php
  app/Filament/Widgets/RecentPingChartWidget.php
  app/Filament/Widgets/RecentUploadChartWidget.php
  app/Filament/Widgets/RecentUploadLatencyChartWidget.php
  config/app.php
Labels: 🎉 feature

#1481 [Chore] Removed deprecated image warning
  app/Filament/Pages/Dashboard.php
  app/Filament/Widgets/DeprecatedImage.php
  resources/views/filament/widgets/deprecated-image.blade.php
Labels: 🧹 chore

#1491 [Chore Round package loss in telegram notification
  app/Listeners/Telegram/SendSpeedtestCompletedNotification.php
  resources/views/telegram/speedtest-completed.blade.php
Labels: 🧹 chore

#1492 [Bug] Fixed result reference in speedtest completed mail
  app/Mail/SpeedtestCompletedMail.php
  resources/views/emails/speedtest-completed.blade.php
Labels: 🐛 bug

#1493 [Feature] Use ping instead of a HTTP get request to check for internet connection
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
  composer.json
  composer.lock
  config/speedtest.php
  docker/8.3/Dockerfile
Labels: 🎉 feature

#1500 [Bug] Use table columns not attributes on results table
  app/Filament/Resources/ResultResource.php
Labels: 🐛 bug

#1507 [Feature] Made checking for internet connection optional
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
  config/speedtest.php
Labels: 🎉 feature

#1511 [Bug] Don't clear cache on settings saved event
  app/Listeners/ClearApplicationCache.php
Labels: 🐛 bug

#1516 [Chore] Removed install command
  app/Console/Commands/InstallCommand.php
Labels: 🧹 chore

#1525 Update README.md
  README.md
Labels: 📖 documentation

#1521 Fix issue with Notify on every speedtest run failing
  app/Mail/SpeedtestCompletedMail.php
  app/Mail/SpeedtestThresholdMail.php
Labels: 🐛 bug

#1532 swapped download and upload charts
  app/Filament/Pages/Dashboard.php
Labels: 🧹 chore

#1533 [Feature] Write the server id to the result on failed tests
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
Labels: 🎉 feature

#1568 [Chore] Added public dashboard middleware
  app/Events/SpeedtestCompleted.php
  app/Events/SpeedtestFailed.php
  app/Events/SpeedtestStarted.php
  app/Http/Controllers/HomeController.php
  app/Http/Middleware/PublicDashboard.php
  app/Jobs/InfluxDBv2/WriteCompletedSpeedtest.php
  app/Jobs/Speedtests/ExecuteOoklaSpeedtest.php
  app/Jobs/TruncateResults.php
  app/Mail/SpeedtestCompletedMail.php
  app/Mail/SpeedtestThresholdMail.php
  app/Notifications/Telegram/SpeedtestNotification.php
  bootstrap/app.php
  pint.json
  routes/web.php
Labels: 🧹 chore

#1569 [Chore] Bumped duster to v3
  composer.json
  composer.lock
Labels: 🧹 chore

#1561 Add Gotify Notifications via Webhook
  app/Actions/Notifications/SendGotifyTestNotification.php
  app/Filament/Pages/Settings/NotificationPage.php
  app/Listeners/Gotify/SendSpeedtestCompletedNotification.php
  app/Listeners/Gotify/SendSpeedtestThresholdNotification.php
  app/Settings/NotificationSettings.php
  database/settings/2024_02_22_144654_create_gotify_notification_settings.php
  resources/views/gotify/speedtest-completed.blade.php
  resources/views/gotify/speedtest-threshold.blade.php
Labels: 🎉 feature

#1522 Add Support for Slack Notifications via Webhook
  app/Actions/Notifications/SendSlackTestNotification.php
  app/Filament/Pages/Settings/NotificationPage.php
  app/Listeners/Slack/SendSpeedtestCompletedNotification.php
  app/Listeners/Slack/SendSpeedtestThresholdNotification.php
  app/Settings/NotificationSettings.php
  database/settings/2024_02_22_144650_create_slack_notification_settings.php
  resources/views/slack/speedtest-completed.blade.php
  resources/views/slack/speedtest-threshold.blade.php
Labels: 🎉 feature
