Repository alexjustesen/speedtest-tracker, pull requests merged in 2024-03, with the labels that each got.

#1268 [Bug] Result factory with fake data
  database/factories/ResultFactory.php
Labels: 🐛 bug

#1271 [Chore] Refactored Discord notifications to their own listeners
  app/Listeners/Discord/SendSpeedtestCompletedNotification.php
  app/Listeners/Discord/SendSpeedtestThresholdNotification.php
  app/Listeners/SpeedtestCompletedListener.php
  app/Listeners/Threshold/AbsoluteListener.php
  app/Providers/EventServiceProvider.php
  resources/views/discord/speedtest-completed.blade.php
  resources/views/discord/speedtest-threshold.blade.php
  resources/views/telegram/speedtest-threshold.blade.php
Labels: 🧹 chore

#1272 [Chore] Refactored InfluxDBv2 data listener
  app/Jobs/InfluxDBv2/WriteCompletedSpeedtest.php
  app/Listeners/Data/InfluxDb2Listener.php
Labels: 🧹 chore

#1276 [Bug] Use server list when running manual speedtests
  app/Filament/Pages/Dashboard.php
Labels: 🐛 bug

#1277 [Bug] Don't proceed with notifications if absolute threshold disabled
  app/Listeners/Database/SendSpeedtestThresholdNotification.php
  app/Listeners/Discord/SendSpeedtestThresholdNotification.php
  app/Listeners/Mail/SendSpeedtestThresholdNotification.php
  app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
  app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
Labels: 🧹 chore

#1291 [Bug] Don't try to send empty threshold notifications
  app/Listeners/Discord/SendSpeedtestThresholdNotification.php
  app/Listeners/Mail/SendSpeedtestThresholdNotification.php
  app/Listeners/Telegram/SendSpeedtestThresholdNotification.php
  app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
  resources/views/emails/speedtest-completed.blade.php
  resources/views/emails/speedtest-threshold.blade.php
Labels: 🐛 bug

#1300 [Feature] Added packet loss to form view and table
  app/Filament/Resources/ResultResource.php
Labels: 🎉 feature

#1327 Update 2022_08_31_202106_create_results_table.php
  database/migrations/2022_08_31_202106_create_results_table.php
Labels: 🧹 chore

#1332 [Chore] Deprecate general settings site name
  app/Filament/Pages/Settings/GeneralPage.php
  app/Listeners/Webhook/SendSpeedtestCompletedNotification.php
  app/Listeners/Webhook/SendSpeedtestThresholdNotification.php
  app/Settings/GeneralSettings.php
  app/helpers.php
Labels: 🧹 chore

#1333 [Chore] Deprecate general settings public dashboard
  app/Console/Commands/UpdateGeneralSettings.php
  app/Filament/Pages/Dashboard.php
  app/Filament/Pages/Settings/GeneralPage.php
  app/Http/Controllers/HomeController.php
  app/Settings/GeneralSettings.php
  config/speedtest.php
Labels: 🧹 chore
