Repository alexjustesen/speedtest-tracker, pull requests merged in 2025-05, with the labels that each got.

#2195 [Feature] Add Ping and server data to results
  app/Filament/Exports/ResultExporter.php
  app/Filament/Resources/ResultResource.php
  app/Models/Traits/ResultDataAttributes.php
Labels: feature

#2196 2025-05-08 dependency updates
  .github/dependabot.yml
  composer.json
  composer.lock
  docker-compose.yml
  docker/8.3/Dockerfile
  docker/8.3/supervisord.conf
  package-lock.json
  public/js/filament/forms/components/markdown-editor.js
Labels: chore

#2199 Added workflow permissions and updated days and labels
  .github/workflows/stale_issues.yml
Labels: bug

#2176 [Bug] Fix server selection during manual test runs
  app/Jobs/Ookla/SelectSpeedtestServerJob.php
  app/Livewire/Topbar/RunSpeedtestAction.php
Labels: bug

#2204 Run Speedtests from the API
  app/Actions/Ookla/StartSpeedtest.php
  app/Enums/ResultStatus.php
  app/Events/SpeedtestWaiting.php
  app/Filament/Pages/ApiTokens.php
  app/Http/Controllers/Api/V1/ApiController.php
  app/Http/Controllers/Api/V1/RunSpeedtest.php
  app/Jobs/Ookla/ProcessSpeedtestBatch.php
  app/Jobs/Ookla/StartSpeedtestJob.php
  database/migrations/2025_05_19_160458_reset_existing_api_token_abilities.php
  routes/api/v1/routes.php
Labels: feature

#2205 Removed unused dependency timokoerber/laravel-one-time-operations
  composer.json
  composer.lock
Labels: chore

#2206 Refactored running speedtest process
  app/Actions/CheckForScheduledSpeedtests.php
  app/Actions/Ookla/RunSpeedtest.php
  app/Actions/Ookla/StartSpeedtest.php
  app/Http/Controllers/Api/V1/RunSpeedtest.php
  app/Jobs/Ookla/ProcessSpeedtestBatch.php
  app/Livewire/Topbar/RunSpeedtestAction.php
Labels: chore

#2207 Fixed run speedtest server id input
  app/Http/Controllers/Api/V1/RunSpeedtest.php
Labels: bug

#2208 Removed unused InteractsWithSockets trait from event classes
  app/Events/SpeedtestBenchmarkFailed.php
  app/Events/SpeedtestBenchmarkPassed.php
  app/Events/SpeedtestBenchmarking.php
  app/Events/SpeedtestChecking.php
  app/Events/SpeedtestCompleted.php
  app/Events/SpeedtestFailed.php
  app/Events/SpeedtestRunning.php
  app/Events/SpeedtestSkipped.php
  app/Events/SpeedtestStarted.php
  app/Events/SpeedtestWaiting.php
Labels: chore

#2214 [Feature] Convert API page to Resource
  app/Filament/Pages/ApiTokens.php
  app/Filament/Resources/ApiTokenResource.php
  app/Filament/Resources/ApiTokenResource/Pages/ListApiTokens.php
  resources/views/filament/pages/api-tokens.blade.php
Labels: feature

#2222 [Chore] Add CI step to validate and update OpenAPI spec
  .github/workflows/update-openapi.yml
Labels: chore
