Repository alexjustesen/speedtest-tracker, pull requests merged in 2025-07, with the labels that each got.

#2281 [Chore] ARM Speedtest CLI installation method in Dockerfile
  docker/8.3/Dockerfile
Labels: chore

#2294 Fix getting started page text colors on light theme
  resources/views/getting-started.blade.php
Labels: bug

#2295 Added multi-database architecture CI pipeline
  .env.ci
  .github/workflows/ci.yml
  phpunit.xml
Labels: feature
