Repository alexjustesen/speedtest-tracker, pull requests merged in 2025-02, with the labels that each got.

#2015 [Feature] Add server name as a filter in the results
  app/Filament/Resources/ResultResource.php
Labels: 🎉 feature

#2025 [Bug] Cast `prune_results_older_than` as integer
  config/speedtest.php
  routes/console.php
Labels: 🐛 bug

#2030 [Bug] Removed WithoutOverlapping middleware and refactored to use SkipIfBatchCancelled
  app/Jobs/CheckForInternetConnectionJob.php
  app/Jobs/Ookla/BenchmarkSpeedtestJob.php
  app/Jobs/Ookla/CompleteSpeedtestJob.php
  app/Jobs/Ookla/RunSpeedtestJob.php
  app/Jobs/Ookla/SelectSpeedtestServerJob.php
  app/Jobs/Ookla/SkipSpeedtestJob.php
Labels: 🐛 bug

#2031 [Bug] Fixed server name filter
  app/Filament/Resources/ResultResource.php
Labels: 🐛 bug

#2036 [Bug] Fixed panel reverting to light mode
  app/Providers/Filament/AdminPanelProvider.php
  composer.json
  composer.lock
  package-lock.json
  public/css/app/panel.css
  resources/css/filament/admin/tailwind.config.js
  resources/css/filament/admin/theme.css
  resources/css/panel.css
  tailwind.config.js
  vite.config.js
Labels: 🐛 bug

#2037 [Bug] Fixed models are not being pruned when enabled
  routes/console.php
Labels: 🐛 bug

#2038 [Chore] Removed polling config
  app/Filament/Resources/ResultResource.php
  app/Filament/Resources/ResultResource/Pages/ListResults.php
  app/Filament/Widgets/RecentDownloadChartWidget.php
  app/Filament/Widgets/RecentDownloadLatencyChartWidget.php
  app/Filament/Widgets/RecentJitterChartWidget.php
  app/Filament/Widgets/RecentPingChartWidget.php
  app/Filament/Widgets/RecentUploadChartWidget.php
  app/Filament/Widgets/RecentUploadLatencyChartWidget.php
  app/Filament/Widgets/StatsOverviewWidget.php
  app/Providers/Filament/AdminPanelProvider.php
  config/speedtest.php
Labels: 🧹 chore

#2072 [Chore] Removed docker dependabot updates
  .github/dependabot.yml
Labels: 🧹 chore

#2073 [Chore] 2025-02-23 dependency updates
  composer.json
  composer.lock
  package-lock.json
  public/css/filament/filament/app.css
  public/css/filament/forms/forms.css
  public/js/filament/filament/echo.js
  public/js/filament/forms/components/color-picker.js
  public/js/filament/forms/components/file-upload.js
  public/js/filament/forms/components/rich-editor.js
  public/js/filament/forms/components/select.js
  public/js/filament/forms/components/tags-input.js
  public/js/filament/notifications/notifications.js
  public/js/filament/support/support.js
  public/js/filament/widgets/components/chart.js
  public/js/filament/widgets/components/stats-overview/stat/chart.js
Labels: 🧹 chore
