Repository alexjustesen/speedtest-tracker, pull requests merged in 2025-01, with the labels that each got.

#1963 [Feature] Specify network interface to use
  app/Jobs/Ookla/RunSpeedtestJob.php
  config/speedtest.php
Labels: 🎉 feature

#1964 Laravel 11.37.0 Shift
  composer.json
  composer.lock
Labels: 🧹 chore

#1970 [Chore] Disable API tokens page until API feature is ready
  app/Filament/Pages/ApiTokens.php
Labels: 🧹 chore

#1983 [Feature] Added API endpoints to list, get and get the latest results
  app/Filament/Pages/ApiTokens.php
  app/Http/Controllers/API/HealthCheckController.php
  app/Http/Controllers/Api/V0/GetLatestController.php
  app/Http/Controllers/Api/V1/ApiController.php
  app/Http/Controllers/Api/V1/LatestResult.php
  app/Http/Controllers/Api/V1/ListResults.php
  app/Http/Controllers/Api/V1/ShowResult.php
  app/Http/Resources/V1/ResultResource.php
  composer.json
  composer.lock
  routes/api.php
  routes/api/v1/routes.php
Labels: 🎉 feature

#1984 [Feature] Implement configurable API rate limiting
  app/Providers/AppServiceProvider.php
  config/api.php
  routes/api.php
Labels: 🎉 feature

#1985 [Documentation] Document API endpoints using OpenAPI standard
  app/Http/Controllers/Api/V1/ApiController.php
  app/Http/Controllers/Api/V1/LatestResult.php
  app/Http/Controllers/Api/V1/ListResults.php
  app/Http/Controllers/Api/V1/ShowResult.php
  composer.json
  composer.lock
  openapi.json
Labels: 📖 documentation

#1994 [Feature] Stats API endpoint
  app/Helpers/Bitrate.php
  app/Http/Controllers/Api/V1/ApiController.php
  app/Http/Controllers/Api/V1/Stats.php
  app/Http/Resources/V1/StatResource.php
  routes/api/v1/routes.php
Labels: 🎉 feature

#1998 [Bug] Fixed dynamic filters for `start_at` and `end_at` in ListResults API
  app/Http/Controllers/Api/V1/ListResults.php
Labels: 🐛 bug
