Repository alexjustesen/speedtest-tracker, pull requests merged in 2025-04, with the labels that each got.

#2122 [Chore] Update pull request template to include documentation link se…
  .github/pull_request_template.md
Labels: 🧹 chore

#2121 Laravel 12.6.0 Shift
  composer.json
  composer.lock
  public/css/filament/filament/app.css
  public/js/filament/forms/components/file-upload.js
Labels: 🧹 chore

#2147 [Chore] Added code of conduct and updated labels
  .github/ISSUE_TEMPLATE/BUG_REPORT_FORM.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST_FORM.yml
Labels: chore

#2157 [Bug] Published database config and added DB_SEARCH_PATH as env variable
  config/database.php
Labels: bug

#2150 Add speedtest result bytes to results table
  app/Actions/Influxdb/v2/BuildPointData.php
  app/Filament/Exports/ResultExporter.php
  app/Filament/Resources/ResultResource.php
  app/Http/Resources/V1/ResultResource.php
  app/Jobs/Ookla/RunSpeedtestJob.php
  database/factories/ResultFactory.php
  database/migrations/2025_04_16_000050_update_results_table.php
Labels: feature

#2160 Added allowed IPs
  app/Http/Middleware/AllowedIpAddressesMiddleware.php
  bootstrap/app.php
  config/speedtest.php
Labels: feature
